// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIu6Ay9vpVjdnySU8-uSuJUwZdpO05QUc',
    appId: '1:757892624943:web:c17acf7f5936541a1fccda',
    messagingSenderId: '757892624943',
    projectId: 'todoappflutter-1856b',
    authDomain: 'todoappflutter-1856b.firebaseapp.com',
    storageBucket: 'todoappflutter-1856b.appspot.com',
    measurementId: 'G-KB54NJ2E2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGq6zZTAPBa4Yqq-zsUNlVIPivxmaonO4',
    appId: '1:757892624943:android:45da406b9fdd9b4a1fccda',
    messagingSenderId: '757892624943',
    projectId: 'todoappflutter-1856b',
    storageBucket: 'todoappflutter-1856b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA--H1yz7f-yv_-m7K8rmu4xvKzoFKM5aw',
    appId: '1:757892624943:ios:cb15cc8777ba48621fccda',
    messagingSenderId: '757892624943',
    projectId: 'todoappflutter-1856b',
    storageBucket: 'todoappflutter-1856b.appspot.com',
    iosBundleId: 'com.example.todoFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA--H1yz7f-yv_-m7K8rmu4xvKzoFKM5aw',
    appId: '1:757892624943:ios:cb15cc8777ba48621fccda',
    messagingSenderId: '757892624943',
    projectId: 'todoappflutter-1856b',
    storageBucket: 'todoappflutter-1856b.appspot.com',
    iosBundleId: 'com.example.todoFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIu6Ay9vpVjdnySU8-uSuJUwZdpO05QUc',
    appId: '1:757892624943:web:c15669ab9940c3111fccda',
    messagingSenderId: '757892624943',
    projectId: 'todoappflutter-1856b',
    authDomain: 'todoappflutter-1856b.firebaseapp.com',
    storageBucket: 'todoappflutter-1856b.appspot.com',
    measurementId: 'G-8RQYSRKJTQ',
  );
}
